// City landing pages (SEO). One entry = one page at /laundry-delivery-<slug>.
// Copy is written per city on purpose: Google ignores near-identical pages.
// Keep claims general (no same-day promises). Pickup windows are NOT typed here: they render live from
// site_public_values().zones. `zone` is only needed for cities inside another city's zone (Piedmont, Emeryville).
// region groups cities for the "nearby" links.
// index: true = open to Google (in the sitemap). Leave it off until the page has real local content
// (neighborhoods, local reviews, photos, FAQs): near-identical city pages drag the whole site down.
// Pages without it stay live for visitors but carry noindex and are left out of the sitemap.
module.exports = [
  { name: 'Oakland', slug: 'oakland', index: true, region: 'core',
    intro: "We're based in Oakland, near Fruitvale, so Oakland laundry is washed by our own team a few miles from your door.",
    hoods: ['Rockridge', 'Temescal', 'Fruitvale', 'Lake Merritt', 'Grand Lake', 'Glenview', 'Dimond', 'Montclair', 'Uptown', 'Jack London Square', 'West Oakland', 'Maxwell Park'] },
  { name: 'Berkeley', slug: 'berkeley', index: true, region: 'core',
    intro: "Busy Berkeley households, grad students and UC staff use us to get their weekends back. We pick up across the city, from the flats to the hills.",
    hoods: ['North Berkeley', 'Elmwood', 'Claremont', 'Downtown', 'Southside', 'West Berkeley', 'Thousand Oaks', 'the Berkeley Hills'] },
  { name: 'Alameda', slug: 'alameda', index: true, region: 'core',
    intro: "Our drivers are in Alameda every service day. Leave your bag on the porch and it comes back washed, folded and bundled by family member.",
    hoods: ['the East End', 'the West End', 'Park Street', 'Webster Street', 'Fernside', 'Bay Farm Island'] },
  { name: 'Piedmont', slug: 'piedmont', index: true, region: 'core', zone: 'Oakland',
    intro: "We pick up across Piedmont, from Lower Piedmont up to the hills around Piedmont Park.",
    hoods: [] },
  { name: 'Emeryville', slug: 'emeryville', index: true, region: 'core', zone: 'Oakland',
    intro: "Emeryville is a short hop from our plant in Oakland.",
    hoods: ['the Watergate', 'Bay Street', 'the Park Avenue district'] },
  { name: 'Albany', slug: 'albany', index: true, region: 'core',
    intro: "Albany families get the same next-day service as their Berkeley neighbors, picked up from the door.",
    hoods: ['Solano Avenue', 'Albany Hill', 'University Village'] },
  { name: 'El Cerrito', slug: 'el-cerrito', index: true, region: 'core',
    intro: "We serve El Cerrito from the flats along San Pablo Avenue up into the hills.",
    hoods: ['the El Cerrito Hills', 'Mira Vista', 'the San Pablo Avenue corridor'] },
  { name: 'Kensington', slug: 'kensington', index: true, region: 'core',
    intro: "We pick up across Kensington, from Arlington Avenue to the Berkeley and Albany borders.",
    hoods: [] },
  { name: 'Richmond', slug: 'richmond', index: true, region: 'core', zone: 'Berkeley',
    intro: "Richmond customers leave their bag at the door and get it back washed, folded and bundled by family member.",
    hoods: [] },
  { name: 'San Leandro', slug: 'san-leandro', index: true, region: 'south',
    intro: "San Leandro is one of the closest cities to our Oakland base.",
    hoods: ['Estudillo Estates', 'Broadmoor', 'Bay-O-Vista', 'Washington Manor', 'the Marina'] },
  { name: 'San Lorenzo', slug: 'san-lorenzo', index: true, region: 'south',
    intro: "San Lorenzo households get pickup at the door and their laundry back folded, without a trip to the laundromat.",
    hoods: [] },
  { name: 'Castro Valley', slug: 'castro-valley', index: true, region: 'south',
    intro: "From Castro Valley Boulevard to the canyons, we pick up and deliver across Castro Valley.",
    hoods: ['Five Canyons', 'Palomares Hills'] },
  { name: 'Hayward', slug: 'hayward', index: true, region: 'south',
    intro: "Hayward families and seniors use us to take laundry day off their list.",
    hoods: ['Downtown Hayward', 'the Hayward Hills', 'Fairway Park', 'Tennyson-Alquire'] },
  { name: 'Union City', slug: 'union-city', index: true, region: 'south',
    intro: "We pick up in Union City and return everything washed, folded and ready to put away.",
    hoods: ['Alvarado', 'Decoto'] },
  { name: 'Fremont', slug: 'fremont', index: true, region: 'south',
    intro: "Fremont is one of our longest drives, and it costs the same as everywhere else we serve.",
    hoods: ['Mission San Jose', 'Niles', 'Centerville', 'Irvington', 'Warm Springs'] },
  { name: 'Newark', slug: 'newark', index: true, region: 'south',
    intro: "Newark customers get the same service as Oakland. We pick up, wash in-house, fold and return.",
    hoods: [] },
  { name: 'Orinda', slug: 'orinda', index: true, region: 'lamorinda',
    intro: "We pick up across Orinda, from Orinda Village to Sleepy Hollow and El Toyonal.",
    hoods: [] },
  { name: 'Moraga', slug: 'moraga', index: true, region: 'lamorinda',
    intro: "Moraga families use us to hand off the never-ending pile of school and sports laundry.",
    hoods: [] },
  { name: 'Lafayette', slug: 'lafayette', index: true, region: 'lamorinda',
    intro: "Lafayette households get door-to-door pickup and laundry back folded and bundled by family member.",
    hoods: [] },
  { name: 'Walnut Creek', slug: 'walnut-creek', index: true, region: 'lamorinda',
    intro: "From downtown Walnut Creek to Rossmoor, we pick up and deliver to your door, a big help for anyone who'd rather not haul baskets.",
    hoods: ['Downtown', 'Northgate', 'Rossmoor'] },
  { name: 'Pleasant Hill', slug: 'pleasant-hill', index: true, region: 'lamorinda',
    intro: "Pleasant Hill customers leave their bag out and get it back washed fragrance-free and neatly folded.",
    hoods: [] },
  { name: 'Concord', slug: 'concord', index: true, region: 'lamorinda',
    intro: "We pick up across Concord and bring your laundry back washed at our own plant and folded.",
    hoods: [] },
  { name: 'Martinez', slug: 'martinez', index: true, region: 'lamorinda',
    intro: "Martinez households can hand off laundry day. We pick up, wash, fold and deliver.",
    hoods: [] },
  { name: 'San Francisco', slug: 'sf', index: true, region: 'sf',
    intro: "San Francisco pickups run in the evening. Your laundry crosses the Bay Bridge to our own plant in Oakland, where our team washes and folds it. We never hand it to a third party.",
    hoods: ['the Mission', 'Noe Valley', 'Bernal Heights', 'SoMa', 'Mission Bay', 'Potrero Hill', 'Dogpatch', 'Hayes Valley', 'Pacific Heights', 'the Marina', 'the Richmond', 'the Sunset'] },
];
